config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "requests/approve_request/:id" => "requests#approve_request"
  get "requests/disapprove_request/:id" => "requests#disapprove_request"
  resources :requests
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  private
  # Finds the User with the ID stored in the session with the key
  # :current_user_id This is a common way to handle user login in
  # a Rails application; logging in sets the session value and
  # logging out removes it.
  def current_user
    @_current_user ||= session[:current_user_id] &&
      User.find_by(id: session[:current_user_id])
  end
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :users, optional: true;
end

app/models/user.rb
class User < ApplicationRecord
  has_many :requests
  has_secure_password
  validates :password, length: { minimum: 6 }
  validates :username, presence: true, length: { maximum: 20 }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
		@requests = Request.where(user_id: session['user_id'])
		@requestsadmin = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def approve_request
	@request = Request.find(params[:id])
    @request.status = "Approved"
    @request.save
    redirect_to requests_path
  end
  
  def disapprove_request
	@request = Request.find(params[:id])
    @request.status = "Disapproved"
    @request.save
    redirect_to requests_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:user_id, :item, :quantity, :status, :request_date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(username: params[:session][:username].downcase)
		if user && user.authenticate(params[:session][:password])
		  session[:user_id]=user.id
		  redirect_to new_request_path
		else
		  flash.now[:danger] = 'Invalid email/password combination'
		  render 'new'
		end
    end

	def destroy
	  session[:user_id] = nil
	  flash[:notice] = "Logged out successfully"
	  redirect_to root_path
	end

	private

	def login_user!(user)
	  session[:user_id] = user.id
	  flash[:notice] = "Welcome, you're now logged in"
	  redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :password, :department, :user_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <title>GSOEF-FP</title>
     <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/bower_components/font-awesome/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/bower_components/Ionicons/css/ionicons.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/dist/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="https://adminlte.io/themes/AdminLTE/dist/css/skins/_all-skins.min.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
   <style>
    .example-modal .modal {
      position: relative;
      top: auto;
      bottom: auto;
      right: auto;
      left: auto;
      display: block;
      z-index: 1;
    }

    .example-modal .modal {
      background: transparent !important;
    }
  </style>
   </head>
  <body>
    <%= yield %>
  <!-- jQuery 3 -->
<script src="https://adminlte.io/themes/AdminLTE/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="https://adminlte.io/themes/AdminLTE/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- SlimScroll -->
<script src="https://adminlte.io/themes/AdminLTE/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="https://adminlte.io/themes/AdminLTE/bower_components/fastclick/lib/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="https://adminlte.io/themes/AdminLTE/dist/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="https://adminlte.io/themes/AdminLTE/dist/js/demo.js"></script>
<!-- DataTables -->
<script src="https://adminlte.io/themes/AdminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="https://adminlte.io/themes/AdminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script>
  $(document).ready(function () {
    $('.sidebar-menu').tree()
  })
</script> 
<script>
  $(function () {
    $('#example1').DataTable()
    $('#example2').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : false,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
  })
</script>
  </body>
</html>

app/views/requests/edit.html.erb
<%= render 'form', request: @request %>

app/views/requests/index.html.erb
<div class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="../../index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>GSOEF-</b>FP</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </nav>
  </header>

  <!-- =============================================== -->

  <!-- Left side column. contains the sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">CONTROLS</li>
        <li>
          <a href = "http://localhost:3000/login">
            <i class="fa fa-power-off"></i> <span>Logout</span>
          </a>
        </li>
        </ul>
		
    </section>
    <!-- /.sidebar -->
  </aside>
  <!-- =============================================== -->
	
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
   <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Dashboard
        <small>Main page</small>
      </h1>
	  <ol class="breadcrumb">
	   <li><i class="fa fa-user"></i> Department: </li>
	   <li><%=User.where("id = ?", session['user_id']).pluck("department").first%></li>
	  </ol>
    </section>
	
    <!-- Main content -->
    <section class="content">
	<div class="row">
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <a href = "http://localhost:3000/requests"><span class="info-box-icon bg-green"><i class="fa fa-clock-o"></i></span></a>

            <div class="info-box-content">
              <span class="info-box-text">Item Requests</span>
              <span class="info-box-number">
			  <%if User.where("id = ?", session['user_id']).pluck("user_type").first != "administrator"%>
				<%=Request.where(:user_id => session['user_id']).count%>
				<%else%>
				<%=Request.count('user_id')%>
				<%end%>
			  
			  </span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12" id = "departmentID">
          <div class="info-box">
            <a href = "http://localhost:3000/users"><span class="info-box-icon bg-yellow"><i class="fa fa-building"></i></span></a>

            <div class="info-box-content ">
              <span class="info-box-text">Departments</span>
              <span class="info-box-number"><%=User.count('department')%></span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        
      </div>
	</p>
	
	
	<!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Pending / Approved Request</h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<small><%= link_to 'New Request', new_request_path %></small>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button type="button" class="btn btn-primary" onclick="myFunction()">Generate Report</button>

<script>
function myFunction() {
    window.print();
}
</script>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
              <i class="fa fa-minus"></i></button>
          </div>
        </div>
        <div class="box-body">
<!--Ruby codes here-->
	<%if User.where("id = ?", session['user_id']).pluck("user_type").first != "administrator"%>
		 <script>
		 document.getElementById("departmentID").style.display = "none";
		 </script>
		 <p id="notice"><%= notice %></p>
		 <table id="example1" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantity</th>
      <th>Date Requested</th>
	  <th>Status</th>
      <th>Modify Request</th>
       <th>Delete Request</th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.item%></td>
        <td><%= request.quantity%></td>
        <td><%= request.request_date%></td>
        <td><%= request.status%></td>
        <td><%= link_to 'Edit', edit_request_path(request)%></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

	<%else%>
	<p id="notice"><%= notice %></p>
<table id="example1" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantity</th>
      <th>Date Requested</th>
      <th>Status</th>
      <th>Department</th>
      <th colspan = 2>Actions</th>
       <th>Delete Request</th>
    </tr>
  </thead>

  <tbody>
    <% @requestsadmin.each do |request| %>
      <tr>
        <td><%= request.item%></td>
        <td><%= request.quantity%></td>
        <td><%= request.request_date%></td>
        <td><%= request.status%></td>
        <td><%= User.where("id = ?", request.user_id).pluck("department").first%></td>
        <td><%= link_to 'Approve', {:controller => "requests", :action => "approve_request", :id => request.id}, class: "btn btn-primary" %></td>
        <td><%= link_to 'Disapprove', {:controller => "requests", :action => "disapprove_request", :id => request.id}, class: "btn btn-danger" %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
	<%end%>
<br>
 </div>
        
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->


    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>Created By: Ms. Auldrie Anne C. Escobal and Mr. Edmar D. Sanchez</strong> MITS04 Web Engineering
  </footer>
</div>
</div>

app/views/requests/new.html.erb
<%= render 'form', request: @request %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @request.user_id %>
</p>

<p>
  <strong>Item:</strong>
  <%= @request.item %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @request.quantity %>
</p>

<p>
  <strong>Status:</strong>
  <%= @request.status %>
</p>

<p>
  <strong>Status:</strong>
  <%= @request.request_date %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>

  <div class="field">
    <%= form.label :user_type %>
    <%= form.text_field :user_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="../../index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>GSOEF-</b>FP</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </nav>
  </header>

  <!-- =============================================== -->

  <!-- Left side column. contains the sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">CONTROLS</li>
        <li>
          <a href = "http://localhost:3000/login">
            <i class="fa fa-power-off"></i> <span>Logout</span>
          </a>
        </li>
        </ul>
		
    </section>
    <!-- /.sidebar -->
  </aside>
  <!-- =============================================== -->
	
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
   <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Dashboard
        <small>Main page</small>
      </h1>
	  <ol class="breadcrumb">
	   <li><i class="fa fa-user"></i> Department: </li>
	   <li><%=User.where("id = ?", session['user_id']).pluck("department").first%></li>
	  </ol>
    </section>
	
    <!-- Main content -->
    <section class="content">
	<div class="row">
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <a href = "http://localhost:3000/requests"><span class="info-box-icon bg-green"><i class="fa fa-clock-o"></i></span></a>

            <div class="info-box-content">
              <span class="info-box-text">Item Requests</span>
              <span class="info-box-number">
				<%if User.where("id = ?", session['user_id']).pluck("user_type").first != "administrator"%>
				<%=Request.where(:user_id => session['user_id']).count%>
				<%else%>
				<%=Request.count('user_id')%>
				<%end%>
			  </span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12" id = "departmentID">
          <div class="info-box">
            <a href = "http://localhost:3000/users"><span class="info-box-icon bg-yellow"><i class="fa fa-building"></i></span></a>

            <div class="info-box-content ">
              <span class="info-box-text">Departments</span>
              <span class="info-box-number"><%=User.count('department')%></span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        
      </div>
	</p>
	
	
	<!-- Default box -->
      <div class="box">
        <div class="box-header with-border">
           <h3 class="box-title">Departments</h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<small><%= link_to 'New Department', new_user_path %></small>
			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<button type="button" class="btn btn-primary" onclick="myFunction()">Generate Report</button>

<script>
function myFunction() {
    window.print();
}
</script>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
              <i class="fa fa-minus"></i></button>
			  
          </div>
        </div>
        <div class="box-body">
			<p id="notice"><%= notice %></p>
</script>
<table id="example1" class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Department</th>
      <th>User type</th>
      <th>Show</th>
      <th>Modify</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.department %></td>
        <td><%= user.user_type %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

 </div>
        
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->


    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 1.0.0
    </div>
    <strong>Created By: Ms. Auldrie Anne C. Escobal and Mr. Edmar D. Sanchez</strong> MITS04 Web Engineering
  </footer>
</div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<p>
  <strong>Department:</strong>
  <%= @user.department %>
</p>

<p>
  <strong>User type:</strong>
  <%= @user.user_type %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>